# Generated by Django 5.2.6 on 2025-09-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('Mpesa', 'Mpesa'), ('TigoPesa', 'TigoPesa'), ('Visa', 'Visa'), ('Cash', 'Cash on Delivery')], default='Cash', max_length=20),
        ),
    ]
